name = "kotoba-diary"
main = "src/index.js"
compatibility_date = "2026-02-03"
account_id = "9a9cd7ceb41ea85273eb81b508e6f28d"
workers_dev = true

# 静态资源配置
[assets]
directory = "public"
binding = "ASSETS"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "DIARY_KV"
id = "1aa85979f7a04dee8cce40cf18b536f1"
preview_id = "1aa85979f7a04dee8cce40cf18b536f1"
