name = "kotoba-diary"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "9a9cd7ceb41ea85273eb81b508e6f28d"
workers_dev = true

# 静态资源配置
[assets]
directory = "public"
binding = "ASSETS"

# 生产环境
[env.production]
kv_namespaces = [
  { binding = "DIARY_KV", id = "1aa85979f7a04dee8cce40cf18b536f1" }
]

# 预览环境 (本地开发)
[env.preview]
kv_namespaces = [
  { binding = "DIARY_KV", id = "1aa85979f7a04dee8cce40cf18b536f1" }
]
